DROP TABLE IF EXISTS permissao CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;
DROP TABLE IF EXISTS amizade CASCADE;
DROP TABLE IF EXISTS post CASCADE;
DROP TABLE IF EXISTS comentario CASCADE;
DROP TABLE IF EXISTS curtida CASCADE;


CREATE TABLE usuario (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                         nome VARCHAR(255) NOT NULL,
                         email VARCHAR(255) NOT NULL,
                         apelido VARCHAR(50),
                         imagem_perfil VARCHAR(512),
                         data_nascimento DATE NOT NULL,
                         senha VARCHAR(100) NOT NULL,
                         ativo BOOLEAN NOT NULL DEFAULT true

);

ALTER TABLE usuario ADD CONSTRAINT pk_usuario PRIMARY KEY (id);
ALTER TABLE usuario ADD CONSTRAINT uk_usuario_email UNIQUE (email);


CREATE TABLE permissao (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                           funcao VARCHAR(100) NOT NULL,
                           usuario_id BIGINT NOT NULL
);
ALTER TABLE permissao ADD CONSTRAINT pk_permissao PRIMARY KEY (id);
ALTER TABLE permissao ADD CONSTRAINT uk_permissao UNIQUE (funcao, usuario_id);
ALTER TABLE permissao ADD CONSTRAINT fk_permissao_usuario FOREIGN KEY (usuario_id) REFERENCES usuario;

insert into usuario (nome, email, data_nascimento, senha, imagem_perfil) values ( 'Usuario Low Profile', 'anonimo@cwi.com.br', '2000-01-15', '$2a$10$VrIbJURwINOR5HOrWFFTNOwSILsioRJSuOGAg8Luvr9qZDSOl5JXG', 'https://cdn2.iconfinder.com/data/icons/font-awesome/1792/user-secret-512.png');
insert into usuario (nome, email, data_nascimento, senha) values ( 'Mauro Sachs Pereira', 'mauro@cwi.com.br', '2000-01-15', '$2a$10$VrIbJURwINOR5HOrWFFTNOwSILsioRJSuOGAg8Luvr9qZDSOl5JXG');
insert into usuario (nome, email, data_nascimento, senha, imagem_perfil) values ( 'Leo DiCaprio', 'leo@dicaprio.com.br', '1974-11-11', '$2a$10$VrIbJURwINOR5HOrWFFTNOwSILsioRJSuOGAg8Luvr9qZDSOl5JXG', 'https://media.gq.com/photos/566c3affc0f741b430e646c2/3:4/w_996,h_1328,c_limit/Leonardo-Dicaprio-Everything-Oscar.jpg');
insert into usuario (nome, email, data_nascimento, senha, imagem_perfil, apelido) values ( 'Nicolas Cage', 'nick@cage.com.br', '1964-01-07', '$2a$10$VrIbJURwINOR5HOrWFFTNOwSILsioRJSuOGAg8Luvr9qZDSOl5JXG', 'https://www.pngkey.com/png/detail/145-1455308_nicholas-cage-face-png-picture-library-download-memes.png', 'Nick');
insert into usuario (nome, email, data_nascimento, senha, imagem_perfil) values ( 'Morgan Freeman', 'morgan@freeman.com.br', '1937-06-01', '$2a$10$VrIbJURwINOR5HOrWFFTNOwSILsioRJSuOGAg8Luvr9qZDSOl5JXG', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3WF8KCu5Q9PkXY0ya3zNfvTDqMRyWL13MaQ&usqp=CAU');
insert into usuario (nome, email, data_nascimento, senha, imagem_perfil) values ( 'Samuel L. Jackson', 'samuel@jackson.com.br', '1948-12-21', '$2a$10$VrIbJURwINOR5HOrWFFTNOwSILsioRJSuOGAg8Luvr9qZDSOl5JXG', 'https://cdn.jornaldebrasilia.com.br/wp-content/uploads/2022/12/24072946/samuel-l-jackson-1024x575.jpg');
insert into usuario (nome, email, data_nascimento, senha, imagem_perfil) values ( 'Robert D. Junior', 'robert@downey.com.br', '1965-04-04', '$2a$10$VrIbJURwINOR5HOrWFFTNOwSILsioRJSuOGAg8Luvr9qZDSOl5JXG', '');



insert into permissao (funcao, usuario_id) values ('USUARIO', 1);
insert into permissao (funcao, usuario_id) values ('USUARIO', 2);
insert into permissao (funcao, usuario_id) values ('USUARIO', 3);

CREATE TABLE amizade (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                         usuario_1 BIGINT NOT NULL,
                         usuario_2 BIGINT NOT NULL,
                         aceito BOOLEAN NOT NULL
);
ALTER TABLE amizade ADD CONSTRAINT pk_amizade PRIMARY KEY (id);
ALTER TABLE amizade ADD CONSTRAINT uk_amizade UNIQUE (usuario_1,usuario_2);
ALTER TABLE amizade ADD CONSTRAINT fk_amizade_usuario_1 FOREIGN KEY (usuario_1) REFERENCES usuario;
ALTER TABLE amizade ADD CONSTRAINT fk_amizade_usuario_2 FOREIGN KEY (usuario_2) REFERENCES usuario;



CREATE TABLE post (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                      usuario_id BIGINT NOT NULL,
                      titulo_filme VARCHAR(255) NOT NULL,
                      nota_filme VARCHAR(4) NOT NULL,
                      texto VARCHAR(255),
                      data_inclusao TIMESTAMP NOT NULL,
                      privacidade VARCHAR(7) NOT NULL DEFAULT 'PUBLICO'
);


ALTER TABLE post ADD CONSTRAINT pk_post PRIMARY KEY (id);
ALTER TABLE post ADD CONSTRAINT fk_post_usuario_id FOREIGN KEY (usuario_id) REFERENCES usuario;
ALTER TABLE post ADD CONSTRAINT ck_post_nivel CHECK (privacidade IN ('PUBLICO', 'PRIVADO'));


CREATE TABLE comentario (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                            post_id BIGINT NOT NULL,
                            usuario_id BIGINT NOT NULL,
                            texto VARCHAR(255) NOT NULL
);
ALTER TABLE comentario ADD CONSTRAINT pk_comentario PRIMARY KEY (id);
ALTER TABLE comentario ADD CONSTRAINT fk_comentario_usuario_id FOREIGN KEY (usuario_id) REFERENCES usuario;
ALTER TABLE comentario ADD CONSTRAINT fk_comentario_post_id FOREIGN KEY (post_id) REFERENCES post;


CREATE TABLE curtida (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                         post_id BIGINT NOT NULL,
                         usuario_id BIGINT NOT NULL
);
ALTER TABLE curtida ADD CONSTRAINT pk_curtida PRIMARY KEY (id);
ALTER TABLE curtida ADD CONSTRAINT uk_curtida UNIQUE (post_id, usuario_id);
ALTER TABLE curtida ADD CONSTRAINT fk_curtida_usuario_id FOREIGN KEY (usuario_id) REFERENCES usuario;
ALTER TABLE curtida ADD CONSTRAINT fk_curtida_post_id FOREIGN KEY (post_id) REFERENCES post;
